### ISSUE TITLE
Rename writeToH5datarH5df function?

### ISSUE THREAD

**Issue by scottveirs** [JPalmerK/YAWN_functions#2]
Not critical in the short run, but in the long run I think you may have meant something like `writeToH5data-rhdf5` when naming this key function?

`writeToH5datarH5df`
vs
`writeToH5datarhdf5`
or 
`writeToH5data-rhdf5`
or
`writeToH5dataViaRhdf5`?

**Comment by JPalmerK** [comment]
Good point. In the medium term I should comment out the other approach that I was messing around with that did not pan out. That way there shouldn't be any confusion. The two packages are also stepping on each others toes, so nixing one should sort the issue. To do!
